### PR TITLE
basic structure ready

### PR DESCRIPTION
**Pull request by nr072**

### CODE REVIEW

**Comment by maning** [comment]
How's the movement of the website?  Do you need help with review or deployment?

cc @mapconcierge @geohacker @kshitizkhanal7 @govvin

**Comment by nr072** [comment]
@maning 
 
> How's the movement of the website? Do you need help with review or deployment? 
 
Sorry for the late reply. 
Consider this the first draft. Feel free to review (and deploy) to see if everything is alright.

**Comment by govvin** [comment]
@nr072 , Please update the link  to 2016 website to point to the archived version: `https://2016.stateofthemap.asia/` and not to the event registration site.

**Comment by nr072** [comment]
> @nr072 , Please update the link to 2016 website to point to the archived version: `https://2016.stateofthemap.asia/` and not to the event registration site.
 
@govvin 
Done. Thank you.

**Comment by maning** [comment]
@nr072 Can you post a rendered screenshot of all pages in this PR so others can comment on the visual look without pulling and running locally?  This should will allow you to receive immediate feedback.  Thanks!

**Comment by govvin** [comment]
> @nr072 Can you post a rendered screenshot of all pages in this PR so others can comment on the visual look without pulling and running locally? This should will allow you to receive immediate feedback. Thanks!

Try this: https://nr072.github.io/sotm-asia-2019-website/

**Comment by fazlerabbi37** [comment]
please add a cname to https://stateofthemap.asia

cc @mapconcierge

**Comment by maning** [comment]
We are live: https://stateofthemap.asia

I pointed the cname of stateofthemap.asia to the new website for Bangladesh event: https://github.com/sotm-asia/sotm-asia-2019-website/blob/master/CNAME

@mapconcierge  Can you create a subdomain 2018.stateofthemap.asia for the India event last year? https://github.com/sotm-asia/sotm-asia-2018-website/blob/master/CNAME

**Pull request merged**
